export const cinProjects = [
{'cover': '/back-in-a-storm/Still022.jpg',
    'title': 'BACK IN A STORM',
    'director': 'Grace Richardson',
    'type':'Dance Film',
    'genre':'Drama',
    'time': '3 minutes',
    'linktxt':'Full film available to watch now!',
    'link':'https://vimeo.com/785096493/5b2fbc98c8?share=copy',
    'url':'back-in-a-storm',
    'imgs':['/back-in-a-storm/Still001.jpg',
            '/back-in-a-storm/Still004.jpg',
            '/back-in-a-storm/Still005.jpg',
            '/back-in-a-storm/Still006.jpg',
            '/back-in-a-storm/Still010.jpg',
            '/back-in-a-storm/Still012.jpg',
            '/back-in-a-storm/Still013.jpg',
            '/back-in-a-storm/Still017.jpg',
            '/back-in-a-storm/Still018.jpg',
            '/back-in-a-storm/Still021.jpg',
            '/back-in-a-storm/Still022.jpg',
            '/back-in-a-storm/Still024.jpg',
            '/back-in-a-storm/Still025.jpg',
            '/back-in-a-storm/Still027.jpg',
            '/back-in-a-storm/Still028.jpg']
},

{'cover': '/leo-lets-it-rain/Still005.jpg',
    'title': 'LEO LETS IT RAIN',
    'director': 'Jasmin Prophete',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': 'Runtime TBD',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'leo-lets-it-rain',
    'imgs':['/leo-lets-it-rain/Still001.jpg',
            '/leo-lets-it-rain/Still002.jpg',
            '/leo-lets-it-rain/Still003.jpg',
            '/leo-lets-it-rain/Still004.jpg',
            '/leo-lets-it-rain/Still005.jpg',
            '/leo-lets-it-rain/Still006.jpg',
            '/leo-lets-it-rain/Still007.jpg',
            '/leo-lets-it-rain/Still008.jpg',
            '/leo-lets-it-rain/Still009.jpg',
            '/leo-lets-it-rain/Still010.jpg',
            '/leo-lets-it-rain/Still011.jpg',
            '/leo-lets-it-rain/Still013.jpg']
},
{'cover': '/music-coma/Still001.jpg',
    'title': 'MUSIC COMA',
    'director': 'Rose Sutton',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': 'Runtime TBD',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'music-coma',
    'imgs': ['/music-coma/Still001.jpg',
            '/music-coma/Still002.jpg',
            '/music-coma/Still003.jpg',
            '/music-coma/Still004.jpg',
            '/music-coma/Still005.jpg',
            '/music-coma/Still006.jpg',
            '/music-coma/Still007.jpg',
            '/music-coma/Still008.jpg',
            '/music-coma/Still009.jpg',
            '/music-coma/Still010.jpg',
            '/music-coma/Still011.jpg',
            '/music-coma/Still012.jpg',
            '/music-coma/Still013.jpg']
},
{'cover': '/jinx/Still002.png',
    'title': 'JINX',
    'director': 'Maya Zaleski',
    'type':'Narrative Short',
    'genre':'Psychological Horror ',
    'time': '19 minutes',
    'linktxt':'Teaser available to watch now!',
    'link':'https://www.bymaggiebrill.com/cinematography/jinx#:~:text=Teaser%20available%20to%20watch%20now!',
    'url':'jinx',
    'imgs':['/jinx/Still001.png',
            '/jinx/Still002.png',
            '/jinx/Still003.png',
            '/jinx/Still004.png',
            '/jinx/Still005.png',
            '/jinx/Still006.png',
            '/jinx/Still007.png',
            '/jinx/Still008.png',
            '/jinx/Still009.png',
            '/jinx/Still010.png',
            '/jinx/Still011.png',
            '/jinx/Still012.png',
            '/jinx/Still013.png',
            '/jinx/Still014.png']
},
{'cover': '/everywhere-i-look/Still005.jpg',
    'title': 'EVERYWHERE I LOOK',
    'director': 'November Nolan',
    'type':'Documentary Short',
    'genre':'?',
    'time': 'Runtime TBD',
    'linktxt':'Teaser available to watch now!',
    'link':'https://vimeo.com/910244435/cba7af0ced?share=copy',
    'url':'cinematography/everywhere-i-look',
    'imgs':['/everywhere-i-look/Still001.jpg',
            '/everywhere-i-look/Still002.jpg',
            '/everywhere-i-look/Still003.jpg',
            '/everywhere-i-look/Still004.jpg',
            '/everywhere-i-look/Still005.jpg',
            '/everywhere-i-look/Still006.jpg',
            '/everywhere-i-look/Still007.jpg',
            '/everywhere-i-look/Still008.jpg',
            '/everywhere-i-look/Still009.png',
            '/everywhere-i-look/Still010.png',
            '/everywhere-i-look/Still011.png',
            '/everywhere-i-look/Still012.png',
            '/everywhere-i-look/Still013.png',
            '/everywhere-i-look/Still014.png',
            '/everywhere-i-look/Still015.png']
},
{'cover': '/color-my-grey-street/Still013.jpg',
    'title': 'COLOR MY GREY STREET',
    'director': 'Rose Sutton',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '22 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'color-my-grey-street',
    'imgs':['/color-my-grey-street/Still001.jpg',
            '/color-my-grey-street/Still002.jpg',
            '/color-my-grey-street/Still003.jpg',
            '/color-my-grey-street/Still004.jpg',
            '/color-my-grey-street/Still005.jpg',
            '/color-my-grey-street/Still006.jpg',
            '/color-my-grey-street/Still007.jpg',
            '/color-my-grey-street/Still008.jpg',
            '/color-my-grey-street/Still009.jpg',
            '/color-my-grey-street/Still010.jpg',
            '/color-my-grey-street/Still011.jpg',
            '/color-my-grey-street/Still012.jpg',
            '/color-my-grey-street/Still013.jpg',
            '/color-my-grey-street/Still014.jpg',
            '/color-my-grey-street/Still015.jpg']
},
{'cover': '',
    'title': 'SKY',
    'director': 'Owen Pickette',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '19.5 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/sky',
    'imgs':''
},
{'cover': '/youre-drifting/Still002.jpg',
    'title': 'YOU’RE DRIFTING',
    'director': 'Ben Kaiser',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '14 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'youre-drifting',
    'imgs':['/youre-drifting/Still001.jpg',
            '/youre-drifting/Still002.jpg',
            '/youre-drifting/Still003.jpg',
            '/youre-drifting/Still004.jpg',
            '/youre-drifting/Still005.jpg',
            '/youre-drifting/Still006.jpg',
            '/youre-drifting/Still007.jpg',
            '/youre-drifting/Still008.jpg',
            '/youre-drifting/Still009.jpg']
}
]