export const cinProjects = [
{'cover': '',
    'title': 'BACK IN A STORM',
    'director': 'Grace Richardson',
    'type':'Dance Film',
    'genre':'Drama',
    'time': '3 minutes',
    'linktxt':'Full film available to watch now!',
    'link':'https://vimeo.com/785096493/5b2fbc98c8?share=copy',
    'url':'cinematography/back-in-a-storm',
    'imgs':''
},

{'cover': '',
    'title': 'LEO LETS IT RAIN',
    'director': 'Jasmin Prophete',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': 'Runtime TBD',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/leo-lets-it-rain',
    'imgs':''
},
{'cover': '',
    'title': 'MUSIC COMA',
    'director': 'Rose Sutton',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': 'Runtime TBD',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/music-coma',
    'imgs':''
},
{'cover': '',
    'title': 'JINX',
    'director': 'Maya Zaleski',
    'type':'Narrative Short',
    'genre':'Psychological Horror ',
    'time': '19 minutes',
    'linktxt':'Teaser available to watch now!',
    'link':'https://www.bymaggiebrill.com/cinematography/jinx#:~:text=Teaser%20available%20to%20watch%20now!',
    'url':'cinematography/jinx',
    'imgs':''
},
{'cover': '',
    'title': 'EVERYWHERE I LOOK',
    'director': 'November Nolan',
    'type':'Documentary Short',
    'genre':'?',
    'time': 'Runtime TBD',
    'linktxt':'Teaser available to watch now!',
    'link':'https://vimeo.com/910244435/cba7af0ced?share=copy',
    'url':'cinematography/everywhere-i-look',
    'imgs':''
},
{'cover': '',
    'title': 'COLOR MY GREY STREET',
    'director': 'Rose Sutton',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '22 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/color-my-grey-street',
    'imgs':''
},
{'cover': '',
    'title': 'SKY',
    'director': 'Owen Pickette',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '19.5 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/sky',
    'imgs':''
},
{'cover': '',
    'title': 'YOU’RE DRIFTING',
    'director': 'Ben Kaiser',
    'type':'Narrative Short',
    'genre':'Drama',
    'time': '14 minutes',
    'linktxt':'Coming Soon!',
    'link':'',
    'url':'cinematography/youre-drifting',
    'imgs':''
}
]