export const dirProjects = [
    {'cover': '/how-to-glow-in-the-dark/Still002.jpg',
        'title': 'HOW TO GLOW IN THE DARK',
        'director': 'Writer/Director',
        'type':'Narrative Short',
        'genre':'Drama',
        'time': '11.5 minutes',
        'linktxt':'Northwestern University Women Filmmakers Alliance’s Grant Recipient/nCineYouth Festival Official Selection 2023',
        'link':'',
        'url':'how-to-glow-in-the-dark',
        'imgs':['/how-to-glow-in-the-dark/Still001.jpg',
                '/how-to-glow-in-the-dark/Still003.png',
                '/how-to-glow-in-the-dark/Still004.png',
                '/how-to-glow-in-the-dark/Still005.jpg',
                '/how-to-glow-in-the-dark/Still006.jpg',
                '/how-to-glow-in-the-dark/Still007.jpg',
                '/how-to-glow-in-the-dark/Still008.jpg',
                '/how-to-glow-in-the-dark/Still009.jpg',
                '/how-to-glow-in-the-dark/Still010.jpg']
    },
    
    {'cover': '/walter/Still003.png',
        'title': 'WALTER',
        'director': 'Writer/Director',
        'type':'Narrative Short',
        'genre':'Drama',
        'time': '5.5 minute',
        'linktxt':'Won the Audience Award for Best Film at Prague Film School',
        'link':'',
        'url':'walter',
        'imgs':['/walter/Still001.png',
                '/walter/Still002.png',
                '/walter/Still003.png',
                '/walter/Still004.png',
                '/walter/Still005.png',
                '/walter/Still006.png']
    }
    ]